# ---
# - name: "add Node.js 13"
#   become: true
#   shell: |
#     # Install Node.js LTS version as our base Node.js version
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

# - name: "Install Node.js 13"
#   become: true
#   apt:
#     name: [ "nodejs"]
#     state: latest
#     update_cache: yes
  
#     # Use n version manager to switch to Node.js v13.8.0

# - name: "Install PM2 Globally"
#   npm:
#     name: pm2
#     global: yes    


- name: "add Node.js 13"
  become: true
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

-   name: "Install Node.js 13"
    become: true
    apt:
      name: [ "nodejs"]
    state: latest
    update_cache: yes
  
    # Use n version manager to switch to Node.js v13.8.0

- name: "Install PM2 Globally"
  npm:
    name: pm2
  global: yes    